class couchdb(
  $admin_user = undef,
  $admin_password = undef,
  $basic_realm = undef,
  $bind = '0.0.0.0',
  $buildopts = '',
  $cert_path = '/usr/local/etc/certs',
  $continuous_replication = true,
  $couchdb_database_1 = 'sessions',
  $couchdb_hostname = undef,
  $couchdb_master_hostname = undef,
  $couchdb_masterless_mode = 'false',
  $couchdb_master_ip = undef,
  $cwd = '/usr/local/src',
  $database_dir = '/usr/local/var/lib/couchdb',
  $default_port = '5984',
  $delayed_commits = false,
  $download = 'http://mirror.symnds.com/software/Apache/couchdb/source/1.5.0/apache-couchdb-1.5.0.tar.gz',
  $extension = '.tar.gz',
  $filename = 'apache-couchdb-1.5.0.tar.gz',
  $first_run = 'false',
  $flush_dbs = 'false',
  $foldername = 'apache-couchdb-1.5.0',
  $log_file = '/usr/local/var/log/couchdb/couch.log',
  $log_level = 'error',
  $os_process_limit = '200',
  $require_valid_user = false,
  $rm_build_folder = false,
  $slave_mode = 'false',
  $ulimit = '65536',
  $uuids = 'utc_random',
  $view_index_dir = '/usr/local/var/lib/couchdb',
) {

  include couchdb::package,
          couchdb::install,
          couchdb::service,
          couchdb::ssl
}